version: "3"
services: 
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./:/projects"
    tty: true
    command: flask run -h 0.0.0.0 -p 5000
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py